#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

until python /check_db_service.py; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 2
done
>&2 echo 'PostgreSQL is available'

exec "$@"
